### PR TITLE
Augment tooBusyLag value (fixes message "I'm busy right now, try again later)

### PR DESCRIPTION
**Pull request by fflorent**
## Problem
- See #47 

## Solution
- Augment the default value for `tooBusyLag`
- Rename `config.json.example` to `config.json.default` which is a more accurate name

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results

---

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/codimd_ynh%20PR-NUM-%20(USERNAME)/)

### CODE REVIEW

**Comment by fflorent** [comment]
@lapineige @ericgaspar I am not sure how I should test using `Package_check`. Or should I let you do that for me?

**Review by lapineige — APPROVED** [review]
I'm fine with that 1s value

**Comment by ericgaspar** [comment]
I had explanations with the CodiMD developers on this option and how much we should set it:

> for the demo instance I pushed it to 200, iirc. Depending on the machine 1000 might be an option. It basically means that CodiMD doesn't send out a "I'm busy" note even when it takes a second to answer requests. I wouldn't necessarily set it to 1000, no. But increasing it is fine and might be a good idea for low compute devices like a old generation raspberry Pi as soon as you get load on it.

**Comment by fflorent** [comment]
> I had explanations with the CodiMD developers on this option and how much we should set it:
> 
> > for the demo instance I pushed it to 200, iirc. Depending on the machine 1000 might be an option. It basically means that CodiMD doesn't send out a "I'm busy" note even when it takes a second to answer requests. I wouldn't necessarily set it to 1000, no. But increasing it is fine and might be a good idea for low compute devices like a old generation raspberry Pi as soon as you get load on it.

Thanks for your feedback. What value do you think it would be fair?

Florent

**Comment by lapineige** [comment]
If that value is reached, the server don't let you interact with your document, right ?

I'd prefer a relatively high value and laggy service on old hardware, but users being able to actually use it, instead of blocking them.

**Comment by fflorent** [comment]
> If that value is reached, the server don't let you interact with your document, right ?

Yes.

**Comment by lapineige** [comment]
Then 1s is fine for me. Or anything between 0,5 and 1s.

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
